name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: linting
        uses: alexanderdamiani/pylinter@v1.3.0
        with:
          python-root: '.'
          flake8-flags: ''
          mypy-flags: ''
          fail-on-isort: true
    - name: Test with pytest
      run: |
        # calling via python will also add the current directory to sys.path
        python -m pytest